### ISSUE TITLE
На какой версии v8Reader и precommit1c основана твоя версия?

### ISSUE THREAD

**Issue by artbear** [demidych/precommit1C_1Script#1]

**Comment by demidych** [comment]
Скачивал с git архивами:
- precommit1c-develop.zip - 20.05.16. В v8files-extractor.os версия 2.0.2
- v8Reader-master.zip - 11.01.16. В history.txt версия 1.12

Скорее всего эти версии и использовал.

**Comment by artbear** [comment]
Добавь эту инфу в ридми, пожалуйста.

**Comment by demidych** [comment]
Добавил.

**Comment by bambr1975** [comment]
По поводу v8Reader-master.zip от 11.01.16 - это, конечно, неправда. Эти изменения были тогда только в develop. Но это вообще-то неважно. А обновление на новую версию v8Reader планируется? Тут @pumbaEO https://gitter.im/xDrivenDevelopment/precommit1c?at=5791e3e87d3b50ce77b9d4e9 вроде какие-то идеи по этому поводу предлагал

**Comment by demidych** [comment]
Честно говоря просто не помню что брал. Я в это все влез где-то полгода назад и в тот момент качал все подряд.
Попробую обновить как время появится.

**Comment by demidych** [comment]
@bambr1975 Обновил

**Comment by bambr1975** [comment]
А кстати, почему https://github.com/demidych/precommit1C_1Script/blob/master/precommit.os#L5275 закомментировано? Принципиально неудобно видеть mxl в виде txt?

**Comment by demidych** [comment]
В oscript нет ТабличныйДокумент

**Comment by bambr1975** [comment]
Ах, как хотелось, чтобы http://yoksel.net.ru/ParametryKomandnojjStroki здесь был txt)))) Да и честно говоря http://yoksel.net.ru/forum/topic.php?id=436 - "Версия формата файла не поддерживается".  Однако Йоксель работает в v8: http://yoksel.net.ru/ComServer  (4-е сообщение в http://yoksel.net.ru/Pomoshh'Proektu?show_comments=1). И Oscript поддерживает Com-объекты.

**Comment by nixel2007** [comment]
Не надо ком-объекты, пожалуйста)

**Comment by bambr1975** [comment]
https://github.com/xDrivenDevelopment/precommit1c/pull/80#issuecomment-213059942
по поводу того, что не надо ком-объекты. Что думаешь делать с Новый COMОбъект("VBScript.RegExp")  ? В oscript для таких целей есть http://oscript.io/syntax/page/%d0%a0%d0%b5%d0%b3%d1%83%d0%bb%d1%8f%d1%80%d0%bd%d0%be%d0%b5%d0%92%d1%8b%d1%80%d0%b0%d0%b6%d0%b5%d0%bd%d0%b8%d0%b5

**Comment by demidych** [comment]
В таком виде не вижу смысла что-то переделывать. Я бы сначала привел код к нормальному виду: удалил завязки на интерфейс, вычистил лишнее и т.д. Но есть надежда, что 1С сделает нормальную выгрузку обработок в файлы (которая не будет  терять типы реквизитов при выгрузке из чистой конфигурации). Поэтому пока жду.

Ну и есть опасение, что используя то, чего нет в 1С становится непонятно зачем вообще использовать oscript, т.к. теряется "фишка", что этот код может понять 1С-ник. Можно тогда использовать другие языки, например javascript.

**Comment by pumbaEO** [comment]
Надежды нет. На ближайший год, точно нет. Потом у них сработает time bomb и
они нехотя признают правоту. Т.е. где-то через 2 года возможно сделают.

01 авг. 2016 г. 8:02 пользователь "demidych" notifications@github.com
написал:

**Comment by artbear** [comment]
> Ну и есть опасение, что используя то, чего нет в 1С становится непонятно зачем вообще использовать oscript, т.к. теряется "фишка", что этот код может понять 1С-ник. Можно тогда использовать другие языки, например javascript.

Мы разделяем язык и прикладную часть 1script. язык = языку 1С, а вот прикладная часть может отличаться со сохранением совместимости с 1С.
Использование COM-объектов не особо совместимо с 1С, например, в Линуксе или на сервере могут быть проблемы.

**Comment by bambr1975** [comment]
https://gitter.im/xDrivenDevelopment/precommit1c?at=5858280e7a3f79ef5d77553a 
Пинг?
